## MESSAGES
class MSG:
    AUBA = 'AUBA'
    auba_version = '1.2'
    
    # CLIENT
    BACKUP_TO = 'BACKUP_TO'
    FREE_UP_SPACE_TO = 'FREE_UP_SPACE_TO'
    REGISTER_ME = 'REGISTER_ME'
    PASSWD = 'PASSWD'
    FILE_DATETIME_UPDATE = 'FILE_DATETIME_UPDATE'
    TOTAL_SIZE = 'TOTAL_SIZE'
    FILE_NAME = 'FILE_NAME'
    FILE_SIZE = 'FILE_SIZE'
    CHANGES = 'CHANGES'
    ADDITION = 'ADDITION'
    REMOVAL = 'REMOVAL'
    AUBA = 'AUBA'
    FILE_COUNT = 'FILE_COUNT'
    FILE_OCCURRED = 'FILE_OCCURRED'

    # SERVER
    OK = 'OK\n'
    REGISTER_OK = 'REGISTER_OK\n'
    I_DONT_KNOW_YOU = 'I_DONT_KNOW_YOU\n'
    WRONG_TIME = 'WRONG_TIME\n'
    INSUFFICIENT_SPACE = 'INSUFFICIENT_SPACE\n'
    CONTRACT_ERROR = 'CONTRACT_ERROR\n'
    WRONG_PASSWD = 'WRONG_PASSWD\n'
    INTERNAL_ERRO = 'INTERNAL_ERRO\n'
    COMPLETE_UPDATE = 'COMPLETE_UPDATE\n'
    ERROR_IN_UPDATE = 'ERROR_IN_UPDATE\n'
